### ISSUE TITLE
[Bug] Account Switcher

### ISSUE THREAD

**Issue by alsoGAMER** [juby210-PL/EnhancedDiscord-plugins#1]
The plugin isn't working properly.

Here the error in the console:
```
[EnhancedDiscord] [Account Switcher] Failed to load:
ReferenceError: $ is not defined
    at Plugin.load (/home/user/Documents/EnhancedDiscord/plugins/account_switcher.js:12:9)
    at loadPlugin (/home/user/Documents/EnhancedDiscord/dom_shit.js:88:16)
    at process.<anonymous> (/home/user/Documents/EnhancedDiscord/dom_shit.js:149:9)
(anonymous) @ faaa66cf8d9f85153c86.js:16
```

**Comment by Juby210** [comment]
Use this repository as an archive, probably none of my ED plugins works without errors now
